
n = 2

assert n > 3
# Traceback throws AssertionError
# Process finished with exit code 1
